### ISSUE TITLE
Align metric names with "official" micrometer names

### ISSUE THREAD

**Issue by fkoehler** [kontainers/micrometer-akka#47]
In our project we are using micrometer-akka to monitor our akka dispatchers/thread pools but also the official micrometer `ExecutorServiceMetrics` to monitor other thread pools which are not managed by akka.

This works all nicely but what is not so nice is that the metrics names of micrometer-akka are not the same as the official micrometer ones which adds burden when configuring the monitoring system and adds rethinking in the head.

In addition to that the explicit naming of the type of dispatcher in the metric name, i.e. `akka_dispatcher_forkjoinpool_active_thread_count` vs `akka_dispatcher_threadpool_executor_active_thread_count` adds redundancy in the names which could be better be expressed as tags.

Following the "official" micrometer scheme here:
 https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java#L180-L236 I'd suggest for example the following metrics:

```
akka_dispatcher_forkjoinpool_active_thread_count
tags:
- dispatcher_name:akka.remote.default-remote-dispatcher
```

would become:

```
executor.active
tags:
- name:akka.remote.default-remote-dispatcher
- type:forkjoinpool
```

This way the same graph could work with both inputs.
The problem is though that micrometer does not set the `type` tag currently which is extra information micrometer akka got.  I've created https://github.com/micrometer-metrics/micrometer/issues/1680 for that.

Of course this is more "cosmetic" but I guess since we do this for micrometer it makes sense to align the way the metrics are named and generated.

 I can provide a PR for that.

**Comment by pjfanning** [comment]
Would an approach like https://github.com/kontainers/micrometer-akka/tree/executor-service-metrics make sense? I haven't rewritten the unit tests so they will fail.

If I were to release this, I would probably add a config flag that controlled whether dispatcher metrics were in existing format or in the new format (at least for a release or 2).

**Comment by fkoehler** [comment]
Please see my comment here: https://github.com/kontainers/micrometer-akka/commit/06cd3cc0cf38410c81934cef3c6388dda92eeb7d

A config flag makes sense to not break other consumers for some releases.

**Comment by pjfanning** [comment]
https://github.com/kontainers/micrometer-akka/pull/49 was merged - I need to add some test coverage but I will publish new snapshot jars (0.110-SNAPSHOT) 

To enable new behaviour, set conf value

`micrometer.akka.executor-service.style="core"`
