### ISSUE TITLE
Can not get akka metrics from spring boot using micrometer with prometheus embedded. 

### ISSUE THREAD

**Issue by lubinson** [kontainers/micrometer-akka#6]
Hi,

I am using akka in Spring Boot.  Micrometer is used for metrics. Prometheus endpoint is exposed by Spring Boot.  App configuration like below in application.properties:
```
management.server.port=9000
management.server.ssl.enabled=false
management.endpoints.web.exposure.include=info,health,prometheus
```

This configuration works fine for metrics generated by prometheus and application metrics generated by micrometer registery. 

Now I try to use micrometer-akka by below steps:
```
1, add 'io.kontainers:micrometer-akka_2.12:0.9.0' in gradle.build.
2, add default micrometer-akka configuration in application.conf.
3, add -javaagent:/aspectjweaver-1.9.1.jar in java command.
```

Application started. Akka works fine as before. I don't know the default akka metrics names, so I use words `akka` and `actor` to find in prometheus query but can't find.  I think it should be some akka system metrics can be found there. 

A warning is encountered when application started, I am not sure it is related. 
```
[LaunchedURLClassLoader@51e2adc7] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
```

I am using `Java 10`. 

Thanks.

**Comment by pjfanning** [comment]
Did you set the registry as in https://github.com/pjfanning/micrometer-akka-sample/blob/master/src/main/scala/com/example/akka/Main.scala ?
